-- Fresh installation baseline matching the supplied application.
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  role varchar(255) NOT NULL
);

CREATE TABLE games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  genre varchar(255),
  players varchar(255),
  category varchar(255) NOT NULL,
  description text,
  image_url varchar(255),
  emoji varchar(255),
  color varchar(255),
  active boolean
);

CREATE TABLE events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  description text,
  short_description varchar(255),
  event_date date NOT NULL,
  start_time time(6),
  end_time time(6),
  location varchar(255),
  capacity integer,
  status varchar(255),
  registration_open boolean,
  image_url varchar(255)
);

CREATE TABLE tournaments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  game_id bigint NOT NULL REFERENCES games(id),
  start_date date,
  format varchar(255),
  description text,
  location varchar(255),
  max_teams integer,
  registration_open boolean,
  status varchar(255)
);

CREATE TABLE gallery_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  description text,
  image_url varchar(255) NOT NULL,
  event_date date,
  active boolean,
  created_at timestamp(6) NOT NULL
);

CREATE TABLE team_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  role varchar(255) NOT NULL,
  bio text,
  image_url varchar(255),
  email varchar(255),
  linkedin_url varchar(255),
  discord_username varchar(255),
  active boolean,
  display_order integer
);

CREATE TABLE membership_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(255) NOT NULL,
  last_name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  program varchar(255),
  motivation text,
  status varchar(255),
  created_at timestamp(6) NOT NULL
);

CREATE TABLE suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  description text,
  preferred_date varchar(255),
  status varchar(255),
  created_at timestamp(6) NOT NULL
);

CREATE TABLE event_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  event_id bigint NOT NULL REFERENCES events(id),
  status varchar(255),
  registered_at timestamp(6) NOT NULL,
  CONSTRAINT uk_user_event UNIQUE(user_id,event_id)
);

CREATE TABLE tournament_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  tournament_id bigint NOT NULL REFERENCES tournaments(id),
  status varchar(255),
  registered_at timestamp(6) NOT NULL,
  CONSTRAINT uk_user_tournament UNIQUE(user_id,tournament_id)
);