import { PixelIcon } from '../components/PixelIcon';
import { useState } from 'react';
import { Card, Badge, GradBtn, Input } from '../components/ui';
import { DataState, Feedback, Modal } from '../components/States';
import { useAuth } from '../services/auth';
import { apiRequest, ApiError } from '../services/api';
import { useData, dateLabel, type Game, type Registration, type TournamentRegistration, type Suggestion } from '../services/data';
const INTERESTS=['Gaming','Esports','Board Games','Casual Games','Community','Events'];
export function ProfilePage() {
 const {user,refresh,logout}=useAuth();
 const games=useData<Game[]>('/users/me/favorite-games'),events=useData<Registration[]>('/events/my-registrations'),tournaments=useData<TournamentRegistration[]>('/tournaments/my-registrations'),suggestions=useData<Suggestion[]>('/suggestions/mine');
 const [editing,setEditing]=useState(false),[form,setForm]=useState({name:user?.name||'',program:user?.program||'',interests:user?.interests||[]});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 if(!user)return null;
 async function action(path:string,method:string,done:()=>void,body?:unknown){setBusy(true);setError('');setMessage('');try{await apiRequest(path,{method,...(body?{body:JSON.stringify(body)}:{})});done();setMessage('Your changes have been saved.');}catch(e){setError(e instanceof ApiError?[e.message,...Object.values(e.fields)].join(' · '):(e as Error).message);}finally{setBusy(false);}}
 return <div className="py-16 px-6 max-w-4xl mx-auto">
  <div className="flex flex-wrap items-center justify-between gap-6 mb-12"><div className="flex items-center gap-4 sm:gap-6 min-w-0 max-w-full"><div className="w-20 h-20 rounded-full grad-bg flex items-center justify-center text-2xl font-black shrink-0">{user.name.split(' ').map(p=>p[0]).join('').slice(0,2)}</div><div className="min-w-0"><h1 className="text-2xl font-black break-words">{user.name}</h1><p className="text-sm mt-1 text-[var(--muted-foreground)] break-all">{user.email}</p>{user.program&&<p className="text-sm mt-1 text-[var(--muted-foreground)]">{user.program}</p>}<div className="flex flex-wrap gap-2 mt-3">{user.interests.map(i=><Badge key={i}>{i}</Badge>)}</div></div></div><button className="text-sm text-[var(--muted-foreground)]" onClick={()=>{logout();window.location.hash='/home';}}>Logout ↗</button></div>
  <Feedback error={error} message={message}/>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 flex flex-col gap-6">
   <Card className="p-6"><h2 className="font-bold text-sm tracking-widest mb-4 text-[var(--secondary-foreground)]"><PixelIcon name="🎮"/> MY GAMES</h2><DataState compact {...games} retry={games.reload} empty={!games.data?.length} title="MAKE ROOM FOR YOUR FAVORITES"><div className="flex flex-wrap gap-2">{games.data?.map(g=><div key={g.id} className="px-3 py-2 rounded-xl text-sm bg-[var(--muted)] flex gap-3 items-center">{g.name}<button disabled={busy} aria-label={`Remove ${g.name} from favorites`} onClick={()=>action(`/users/me/favorite-games/${g.id}`,'DELETE',games.reload)}>×</button></div>)}</div></DataState><a href="#/games" className="inline-block mt-4 px-3 py-2 border border-dashed border-white/20 rounded-xl text-sm text-[var(--muted-foreground)]">+ Discover games</a></Card>
   <Card className="p-6"><h2 className="font-bold text-sm tracking-widest mb-4 text-[var(--secondary-foreground)]"><PixelIcon name="📅"/> MY EVENTS</h2><DataState compact {...events} retry={events.reload} empty={!events.data?.length} title="YOUR NEXT SESSION AWAITS">{events.data?.map(e=><div key={e.id} className="py-4 border-b border-white/5 flex flex-wrap items-center gap-3 justify-between"><div><a href={`#/events/${e.eventId}`} className="font-semibold">{e.eventTitle} ↗</a><p className="text-xs text-[var(--muted-foreground)] mt-1">{dateLabel(e.eventDate)} · {e.status}</p></div>{e.status==='REGISTERED'&&<button disabled={busy} className="text-xs text-rose-300" onClick={()=>action(`/events/${e.eventId}/register`,'DELETE',events.reload)}>Cancel registration</button>}</div>)}</DataState></Card>
   <Card className="p-6"><h2 className="font-bold text-sm tracking-widest mb-4 text-[var(--secondary-foreground)]"><PixelIcon name="🏆"/> MY TOURNAMENTS</h2><DataState compact {...tournaments} retry={tournaments.reload} empty={!tournaments.data?.length} title="YOUR NEXT CHALLENGE AWAITS">{tournaments.data?.map(t=><div key={t.id} className="py-4 border-b border-white/5 flex flex-wrap items-center gap-3 justify-between"><div><p className="font-semibold">{t.title}</p><p className="text-xs text-[var(--muted-foreground)] mt-1">{dateLabel(t.date)} · {t.status}</p></div>{t.status==='REGISTERED'&&<button disabled={busy} className="text-xs text-rose-300" onClick={()=>action(`/tournaments/${t.tournamentId}/register`,'DELETE',tournaments.reload)}>Cancel registration</button>}</div>)}</DataState></Card>
   <Card className="p-6"><h2 className="font-bold text-sm tracking-widest mb-4 text-[var(--secondary-foreground)]"><PixelIcon name="💡"/> MY SUGGESTIONS</h2><DataState compact {...suggestions} retry={suggestions.reload} empty={!suggestions.data?.length} title="GREAT IDEAS START WITH YOU">{suggestions.data?.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-4 py-3 border-b border-white/5"><div><p className="font-medium text-sm">{s.name}</p><p className="text-xs mt-1 text-[var(--muted-foreground)]">{s.type}</p></div><Badge color={s.status==='ACCEPTED'?'#34d399':'#b5179e'}>{s.status}</Badge></div>)}</DataState><a href="#/suggestions" className="inline-block grad-text text-sm mt-5">Share an idea →</a></Card>
  </div><div><Card className="p-6"><h2 className="font-bold text-sm tracking-widest mb-6 text-[var(--secondary-foreground)]">✦ YOUR PIXEL</h2><Badge>{user.role}</Badge><p className="text-sm text-[var(--muted-foreground)] my-5">Make this space yours. Tell the club what you love to play.</p><GradBtn outline onClick={()=>{setForm({name:user.name,program:user.program||'',interests:user.interests});setEditing(true);}}>Edit profile</GradBtn></Card></div></div>
  {editing&&<Modal title="YOUR PIXEL PROFILE" onClose={()=>setEditing(false)}><form className="space-y-5" onSubmit={e=>{e.preventDefault();void action('/users/me','PUT',()=>{void refresh();setEditing(false);},form);}}><Input label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Input label="Program (optional)" value={form.program} onChange={v=>setForm({...form,program:v})}/><fieldset><legend className="text-sm mb-3">Your interests</legend><div className="flex flex-wrap gap-2">{INTERESTS.map(i=><button type="button" key={i} aria-pressed={form.interests.includes(i)} className={`px-3 py-2 rounded-xl text-sm ${form.interests.includes(i)?'grad-bg':'bg-[var(--muted)]'}`} onClick={()=>setForm({...form,interests:form.interests.includes(i)?form.interests.filter(x=>x!==i):[...form.interests,i]})}>{i}</button>)}</div></fieldset><Feedback error={error}/><GradBtn type="submit" disabled={busy}>{busy?'Saving…':'Save profile'}</GradBtn></form></Modal>}
 </div>;
}
